--
-- PostgreSQL database dump
--

-- Dumped from database version 12.2
-- Dumped by pg_dump version 12.2

-- Started on 2020-02-26 15:36:10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 16585)
-- Name: data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.data (
    id integer NOT NULL,
    name text,
    gender text,
    region text,
    didyoucomein text,
    gpabeforenow text,
    english text,
    opinionit text,
    homework text,
    asking text,
    concerntof text,
    testpre text,
    gaming text,
    gpa text
);


ALTER TABLE public.data OWNER TO postgres;

--
-- TOC entry 203 (class 1259 OID 16591)
-- Name: data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.data ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2816 (class 0 OID 16585)
-- Dependencies: 202
-- Data for Name: data; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (199, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (225, '', 'male', 'Northeastern', 'Get-pat', 'Unsatisfy', 'Good', 'Normal', 'Always try', 'Dare', 'Sometimes', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (4, NULL, 'male', 'Eastern​', 'area quota', 'Unsatisfy', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (28, NULL, 'female', 'Central', 'Admissions', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (154, NULL, 'male', 'Eastern', 'Admissions', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (155, NULL, 'male', 'Central', 'Admissions', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (158, NULL, 'female', 'Central', 'Admissions', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I tend to set goals for my studies.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (161, NULL, 'male', 'Central', 'tcas', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (163, NULL, 'male', 'Central', 'Direct examination', 'Good', 'Fair', 'Too Hard', 'Always peel friends', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (168, NULL, 'female', 'Central', 'Admissions', 'Good', 'Fair', 'Normal', 'Always try', 'Dare', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (169, NULL, 'female', 'Central', 'Direct examination', 'Excellent', 'Unsatisfy', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (170, NULL, 'female', 'Southern', 'Portfolio', 'Good', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (172, NULL, 'female', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (173, NULL, 'female', 'Eastern', 'Portfolio', 'Excellent', 'Fair', 'Normal', 'Always try', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (174, NULL, 'female', 'Northern', 'tcas', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (175, NULL, 'male', 'Eastern', 'area quota', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (176, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Unsatisfy', 'Too Hard', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (177, NULL, 'male', 'Central', 'Admissions', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (7, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Unsatisfy', 'Normal', 'Always try', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (8, NULL, 'male', 'Central', 'Portfolio', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (12, NULL, 'female', 'Central', 'area quota', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (13, NULL, 'female', 'Central', 'Direct examination', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (90, NULL, 'male', 'Central', 'O-net', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (15, NULL, 'female', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (17, NULL, 'male', 'Central', 'Admissions', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (18, NULL, 'male', 'Central', 'area quota', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (62, NULL, 'male', 'Central', 'Direct examination', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (22, NULL, 'female', 'Eastern', 'GoodGrade quota', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (25, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (29, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Fair', 'Normal', 'Always try', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (32, NULL, 'male', 'Southern', 'GoodGrade quota', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (34, NULL, 'female', 'Central', 'tcas', 'Good', 'Fair', 'Too Hard', 'Always peel friends', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (35, NULL, 'male', 'Eastern', 'Direct examination', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (38, NULL, 'male', 'Northeastern', 'Portfolio', 'Fair', 'Good', 'Easy', 'Always try', 'Dare', 'Never', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (37, NULL, 'male', 'Eastern', 'Portfolio', 'Excellent', 'Good', 'Easy', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (41, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (42, NULL, 'male', 'Southern', 'Direct examination', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (1, NULL, '﻿male', 'Central', 'Portfolio', 'Excellent', 'Unsatisfy', 'Easy', 'Always try', 'Sometimes', 'Never', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (6, NULL, 'male', 'Central', 'Admissions', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (16, NULL, 'female', 'Central', 'Admissions', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (19, NULL, 'male', 'Eastern', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Always try', 'Dare', 'Never', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (226, '', 'male', 'Northeastern', 'Get-pat', 'Unsatisfy', 'Good', 'Normal', 'Always try', 'Dare', 'Never', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (206, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (233, '', 'male', 'Northeastern', 'Get-pat', 'Unsatisfy', 'Good', 'Normal', 'Always try', 'Dare', 'Never', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (218, '', 'male', 'Northeastern', 'Get-pat', 'Unsatisfy', 'Good', 'Normal', 'Always try', 'Dare', 'Never', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (224, '', 'male', 'Central', 'Portfolio', 'Fair', 'Unsatisfy', 'Too Hard', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (69, NULL, 'male', 'Central', 'Portfolio', 'Fair', 'Unsatisfy', 'Normal', 'Always peel friends', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (71, NULL, 'male', 'Eastern', 'area quota', 'Fair', 'Fair', 'Normal', 'Always peel friends', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (178, NULL, 'female', 'Northern', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (180, NULL, 'male', 'Central', 'Admissions', 'Good', 'Good', 'Too Hard', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (183, NULL, 'female', 'Eastern', 'Portfolio', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'high', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (187, NULL, 'male', 'Central', 'GoodGrade quota', 'Good', 'Good', 'Too Hard', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (188, NULL, 'male', 'Western', 'GoodGrade quota', 'Good', 'Fair', 'Too Hard', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (182, NULL, 'female', 'Central', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (47, NULL, 'female', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Not brave', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (48, NULL, 'female', 'Central', 'Direct examination', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (49, NULL, 'male', 'Northeastern', 'Get-pat', 'Excellent', 'Fair', 'Easy', 'Always try', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (54, NULL, 'male', 'Southern', 'Portfolio', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (55, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (56, NULL, 'female', 'Central', 'Direct examination', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'ฉันมักอ่านบทเรียนล่วงหน้าก่อนเข้าเรียน', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (58, NULL, 'male', 'Eastern', 'tcas', 'Excellent', 'Fair', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (60, NULL, 'male', 'Central', 'Direct examination', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (64, NULL, 'female', 'Central', 'Direct examination', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (65, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (67, NULL, 'male', 'Northern', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (45, NULL, 'male', 'Eastern', 'Direct examination', 'Unsatisfy', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (46, NULL, 'male', 'Central', 'O-net', 'Good', 'Fair', 'Normal', 'Always try', 'Sometimes', 'Never', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (51, NULL, 'male', 'Central', 'Portfolio', 'Excellent', 'Unsatisfy', 'Easy', 'Sometimes', 'Dare', 'Never', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (52, NULL, 'male', 'Northern', 'GoodGrade quota', 'Excellent', 'Good', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (61, NULL, 'male', 'Central', 'area quota', 'Excellent', 'Good', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (63, NULL, 'female', 'Northeastern', 'Direct examination', 'Good', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (66, NULL, 'male', 'Eastern', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Always try', 'Dare', 'Never', 'I tend to set goals for my studies.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (74, NULL, 'female', 'Central', 'Admissions', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Every time', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (75, NULL, 'female', 'Eastern', 'GoodGrade quota', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (78, NULL, 'male', 'Central', 'tcas', 'Excellent', 'Good', 'Normal', 'Always try', 'Dare', 'Never', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (83, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Good', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (85, NULL, 'male', 'Northern', 'tcas', 'Excellent', 'Fair', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (227, '', 'male', 'Northeastern', 'Get-pat', 'Unsatisfy', 'Good', 'Normal', 'Always try', 'Dare', 'Never', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (207, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (234, '', 'male', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Too Hard', 'Sometimes', 'Sometimes', 'Sometimes', 'Read book alone', 'high', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (219, '', 'male', 'Northeastern', 'Get-pat', 'Unsatisfy', 'Good', 'Normal', 'Always try', 'Dare', 'Never', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (95, NULL, 'female', 'Central', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (129, NULL, 'female', 'Central', 'Direct examination', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (143, NULL, 'female', 'Eastern', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (118, NULL, 'male', 'Central', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (70, NULL, 'male', 'Central', 'Portfolio', 'Fair', 'Fair', 'Normal', 'Always try', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (2, NULL, 'male', 'Central', 'tcas', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (91, NULL, 'male', 'Eastern', 'tcas', 'Good', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (3, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (5, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (9, NULL, 'female', 'Eastern', 'Portfolio', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (10, NULL, 'female', 'Eastern', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (11, NULL, 'male', 'Central', 'Direct examination', 'Good', 'Unsatisfy', 'Normal', 'Always peel friends', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (14, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (20, NULL, 'female', 'Central', 'area quota', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (21, NULL, 'female', 'Western', 'Direct examination', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (24, NULL, 'female', 'Eastern', 'GoodGrade quota', 'Excellent', 'Unsatisfy', 'Normal', 'Always peel friends', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (26, NULL, 'female', 'Northeastern', 'tcas', 'Excellent', 'Unsatisfy', 'Too Hard', 'Sometimes', 'Not brave', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (27, NULL, 'female', 'Central', 'area quota', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (30, NULL, 'male', 'Central', 'Direct examination', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (94, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I tend to set goals for my studies.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (97, NULL, 'female', 'Central', 'area quota', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (98, NULL, 'male', 'Eastern', 'GoodGrade quota', 'Excellent', 'Unsatisfy', 'Normal', 'Always try', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (101, NULL, 'male', 'Central', 'Portfolio', 'Unsatisfy', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (111, NULL, 'male', 'Central', 'Admissions', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (113, NULL, 'male', 'Central', 'Admissions', 'Good', 'Excellent', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (119, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (127, NULL, 'male', 'Central', 'tcas', 'Good', 'Unsatisfy', 'Normal', 'Always try', 'Sometimes', 'Never', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (131, NULL, 'male', 'Central', 'tcas', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I tend to set goals for my studies.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (139, NULL, 'female', 'Central', 'Direct examination', 'Excellent', 'Fair', 'Normal', 'Always peel friends', 'Sometimes', 'Sometimes', 'No preparation', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (140, NULL, 'male', 'Central', 'area quota', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (102, NULL, 'female', 'Southern', 'tcas', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (106, NULL, 'male', 'Central', 'Admissions', 'Excellent', 'Excellent', 'Easy', 'Always try', 'Dare', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (109, NULL, 'male', 'Southern', 'Portfolio', 'Excellent', 'Fair', 'Normal', 'Always try', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (110, NULL, 'male', 'Central', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (114, NULL, 'male', 'Central', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (115, NULL, 'female', 'Central', 'GoodGrade quota', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Not brave', 'Never', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (122, NULL, 'male', 'Central', 'O-net', 'Excellent', 'Good', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (124, NULL, 'female', 'Central​', 'GoodGrade quota', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (125, NULL, 'male', 'Eastern', 'GoodGrade quota', 'Good', 'Good', 'Normal', 'Always try', 'Not brave', 'Every time', 'No preparation', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (235, '', 'female', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Too Hard', 'Sometimes', 'Sometimes', 'Sometimes', 'Read book alone', 'high', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (220, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (146, NULL, 'female', 'Central', 'Admissions', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (31, NULL, 'male', 'Central', 'Portfolio', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (33, NULL, 'female', 'Eastern', 'Admissions', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (36, NULL, 'female', 'Northern', 'GoodGrade quota', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (39, NULL, 'male', 'Central​', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (40, NULL, 'female', 'Central', 'GoodGrade quota', 'Good', 'Fair', 'Too Hard', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (43, NULL, 'female', 'Central.', 'Get-pat', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (44, NULL, 'male', 'Central', 'Portfolio', 'Fair', 'Good', 'Normal', 'Sometimes', 'Dare', 'Every time', 'I tend to set goals for my studies.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (50, NULL, 'female', 'Central', 'area quota', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (53, NULL, 'male', 'Central', 'Portfolio', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (57, NULL, 'male', 'Central', 'Admissions', 'Excellent', 'Unsatisfy', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (59, NULL, 'male', 'Central', 'tcas', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (68, NULL, 'female', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (72, NULL, 'male', 'Eastern', 'Direct examination', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (73, NULL, 'male', 'Eastern', 'Direct examination', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (77, NULL, 'female', 'Central', 'Admissions', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Not brave', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (79, NULL, 'male', 'Central', 'GoodGrade quota', 'Good', 'Unsatisfy', 'Too Hard', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (81, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (82, NULL, 'female', 'Eastern', 'tcas', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (86, NULL, 'female', 'Central', 'Portfolio', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (88, NULL, 'male', 'Central', 'tcas', 'Good', 'Good', 'Normal', 'Always try', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (93, NULL, 'female', 'Northeastern', 'Portfolio', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (189, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (190, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (191, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (192, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (147, NULL, 'female', 'Central', 'Admissions', 'Excellent', 'Excellent', 'Normal', 'Sometimes', 'Dare', 'Every time', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (148, NULL, 'female', 'Eastern', 'tcas', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (150, NULL, 'female', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (156, NULL, 'female', 'Central', 'Direct examination', 'Excellent', 'Good', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'I tend to set goals for my studies.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (159, NULL, 'female', 'Eastern', 'GoodGrade quota', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (162, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (164, NULL, 'male', 'Central', 'Admissions', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (165, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (166, NULL, 'male', 'Northern', 'Admissions', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (167, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (171, NULL, 'female', 'Eastern', 'Admissions', 'Excellent', 'Good', 'Normal', 'Always try', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (179, NULL, 'male', 'Central', 'Portfolio', 'Good', 'Fair', 'Normal', 'Always try', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (181, NULL, 'male', 'Eastern', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (157, NULL, 'female', 'Eastern', 'O-net', 'Excellent', 'Fair', 'Normal', 'Always try', 'Sometimes', 'Never', 'I tend to set goals for my studies.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (160, NULL, 'male', 'Western', 'tcas', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (194, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (195, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (197, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (236, '', 'male', 'Central', 'Portfolio', 'Unsatisfy', 'Fair', 'Easy', 'Always peel friends', 'Not brave', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (196, '', 'male', 'undefined', 'Get-pat', 'Unsatisfy', '2', 'Normal', 'Always try', 'Dare', 'undefined', 'Read the book 1 week', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (193, '', 'male', 'Central', 'Portfolio', 'Fair', 'Unsatisfy', 'Too Hard', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (198, '', 'male', 'undefined', 'Get-pat', 'Unsatisfy', '2', 'Normal', 'Always try', 'Dare', 'undefined', 'Read the book 1 week', 'high', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (23, NULL, 'male', 'Eastern', 'tcas', 'Good', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (76, NULL, 'male', 'Northern', 'Direct examination', 'Excellent', 'Fair', 'Easy', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (80, NULL, 'male', 'Eastern', 'area quota', 'Excellent', 'Good', 'Easy', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (84, NULL, 'male', 'Central', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (87, NULL, 'female', 'Eastern', 'tcas', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Never', 'I tend to set goals for my studies.', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (89, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Good', 'Normal', 'Always try', 'Dare', 'Every time', 'I listened carefully to what the teacher was teaching.', 'Dont play', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (92, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (144, NULL, 'female', 'Central', 'Admissions', 'Excellent', 'Fair', 'Too Hard', 'Sometimes', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (138, NULL, 'male', 'Central', 'area quota', 'Good', 'Fair', 'Easy', 'Always peel friends', 'Not brave', 'Every time', 'No preparation', 'high', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (142, NULL, 'female', 'Eastern', 'Portfolio', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (222, '', 'male', 'Central', 'Portfolio', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Never', 'Tutoring with friends', 'medium', 'Appropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (96, NULL, 'male', 'Eastern', 'Direct examination', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (99, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (100, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (103, NULL, 'male', 'Northeastern', 'Portfolio', 'Excellent', 'Fair', 'Normal', 'Always try', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (104, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Fair', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (105, NULL, 'male', 'Eastern', 'Portfolio', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I tend to set goals for my studies.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (107, NULL, 'female', 'Eastern', 'area quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (108, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Good', 'Normal', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (112, NULL, 'female', 'Central', 'GoodGrade quota', 'Good', 'Fair', 'Too Hard', 'Sometimes', 'Not brave', 'Every time', 'I tend to set goals for my studies.', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (116, NULL, 'female', 'Central', 'area quota', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (117, NULL, 'male', 'Central', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (120, NULL, 'female', 'Eastern', 'area quota', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (121, NULL, 'male', 'Central', 'Direct examination', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (123, NULL, 'male', 'Central', 'tcas', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (126, NULL, 'male', 'Central', 'Admissions', 'Good', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (128, NULL, 'female', 'Central', 'Admissions', 'Good', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (130, NULL, 'male', 'Eastern', 'area quota', 'Good', 'Good', 'Normal', 'Sometimes', 'Dare', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (132, NULL, 'male', 'Western', 'Get-pat', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (133, NULL, 'male', 'Central', 'O-net', 'Excellent', 'Good', 'Too Hard', 'Sometimes', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (134, NULL, 'male', 'Western', 'area quota', 'Good', 'Good', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (135, NULL, 'female', 'Northeastern', 'Direct examination', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'SAbout itting and talking nonsense wAbout ith friends while the teacher was teaching', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (136, NULL, 'male', 'Central', 'area quota', 'Fair', 'Fair', 'Normal', 'Always try', 'Sometimes', 'Never', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (137, NULL, 'male', 'Central', 'Admissions', 'Fair', 'Fair', 'Normal', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'Dont play', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (141, NULL, 'male', 'Central', 'Portfolio', 'Unsatisfy', 'Unsatisfy', 'Normal', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (145, NULL, 'female', 'Eastern', 'area quota', 'Good', 'Fair', 'Too Hard', 'Sometimes', 'Sometimes', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (149, NULL, 'male', 'Eastern', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Every time', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (151, NULL, 'male', 'Northern', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (152, NULL, 'male', 'Northern', 'GoodGrade quota', 'Excellent', 'Fair', 'Normal', 'Sometimes', 'Not brave', 'Every time', 'I listened carefully to what the teacher was teaching.', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (153, NULL, 'male', 'Central', 'Direct examination', 'Good', 'Unsatisfy', 'Too Hard', 'Sometimes', 'Sometimes', 'Every time', 'No preparation', 'high', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (184, NULL, 'male', 'Central', 'Portfolio', 'Excellent', 'Unsatisfy', 'Normal', 'Always try', 'Not brave', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (185, NULL, 'male', 'Central', 'Direct examination', 'Excellent', 'Fair', 'Normal', 'Always try', 'Dare', 'Sometimes', 'No preparation', 'medium', 'Inappropriate');
INSERT INTO public.data (id, name, gender, region, didyoucomein, gpabeforenow, english, opinionit, homework, asking, concerntof, testpre, gaming, gpa) OVERRIDING SYSTEM VALUE VALUES (186, NULL, 'male', 'Western', 'Portfolio', 'Excellent', 'Unsatisfy', 'Normal', 'Sometimes', 'Dare', 'Every time', 'No preparation', 'medium', 'Inappropriate');


--
-- TOC entry 2823 (class 0 OID 0)
-- Dependencies: 203
-- Name: data_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.data_id_seq', 236, true);


--
-- TOC entry 2689 (class 2606 OID 16594)
-- Name: data data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.data
    ADD CONSTRAINT data_pkey PRIMARY KEY (id);


-- Completed on 2020-02-26 15:36:10

--
-- PostgreSQL database dump complete
--

